### ISSUE TITLE
Use neocities over weebly for redirect to server invite.

### ISSUE THREAD

**Issue by xillmisa** [thesewerpig/HogSpammer#1]
I will discuss more about it when is responded

**Comment by thesewerpig** [comment]
I'll look into it.

**Comment by xillmisa** [comment]
Unlike weebly, no extra scripts are run in neocities hosted pages and making redirect script shouldn't be hard

**Comment by thesewerpig** [comment]
https://thesewerpig.neocities.org/

**Comment by xillmisa** [comment]
ok cool now

**Comment by xillmisa** [comment]
but replace the weebly link with neocities in index.html
